apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: synaptor-cpu
  name: synaptor-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      run: synaptor-cpu
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: synaptor-cpu
    spec:
      containers:
      - image: seunglab/synaptor
        name: synaptor-cpu
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "python -u worker.py [QUEUE_URL] [TIMEOUT]"]
        resources: 
          requests:
            cpu: 3
        volumeMounts:
        - name: secrets
          mountPath: /root/.cloudvolume/secrets/google-secret.json
          readOnly: true
          subPath: google-secret.json
        - name: secrets
          mountPath: /root/.cloudvolume/secrets/aws-secret.json
          readOnly: true
          subPath: aws-secret.json
# UNCOMMENT THIS IF YOU USE A DATABASE CONNECTION STRING
#        - name: storagestr
#          mountPath: /root/proc_url
#          readOnly: true
#          subPath: proc_url
        - name: boto
          mountPath: /root/.boto
          readOnly: true
          subPath: minimal_boto
      dnsPolicy: Default
      volumes:
      - name: secrets
        secret:
          secretName: secrets
# UNCOMMENT THIS IF YOU USE A DATABASE CONNECTION STRING
#      - name: storagestr
#        secret:
#          secretName: storagestr
      - name: boto
        secret:
          secretName: boto
