apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: synaptor-cpu
  name: synaptor-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      run: synaptor-cpu
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: synaptor-cpu
    spec:
      containers:
      - image: seunglab/synaptor:kube
        name: synaptor-cpu
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "python -u worker.py https://sqs.us-east-1.amazonaws.com/587723909184/synaptor 1200"]
        resources: 
          requests:
            cpu: 6
        volumeMounts:
        - name: secrets
          mountPath: /root/.cloudvolume/secrets/google-secret.json
          readOnly: true
          subPath: microns-seunglab-google-secret.json
        - name: secrets
          mountPath: /root/.cloudvolume/secrets/aws-secret.json
          readOnly: true
          subPath: aws-secret.json
        - name: storagestr
          mountPath: /root/proc_url
          readOnly: true
          subPath: proc_url
        - name: boto
          mountPath: /root/.boto
          readOnly: true
          subPath: minimal_boto_microns
      dnsPolicy: Default
      volumes:
      - name: secrets
        secret:
          secretName: secrets
      - name: storagestr
        secret:
          secretName: storagestr
      - name: boto
        secret:
          secretName: boto
