apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: synaptor-cpu
  name: synaptor-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      run: synaptor-cpu
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: synaptor-cpu
    spec:
      containers:
      - image: seunglab/synaptor:latest
        name: synaptor-cpu
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "python worker.py https://sqs.us-east-1.amazonaws.com/DIGITS/QUEUE_NAME 20"]
        resources: 
          requests:
            cpu: 3
        volumeMounts:
        - name: secrets
          mountPath: /root/.cloudvolume/secrets
          readOnly: true
        - name: storagestr
          mountPath: /root/proc_url
          readOnly: true
        - name: boto
          mountPath: /root/.boto
          readOnly: true
      dnsPolicy: Default
      volumes:
      - name: secrets
        secret:
          secretName: secrets
      - name: storagestr
        secret:
          secretName: proc_url
      - name: boto
        secret:
          secretName: boto
